---
title: "My Adventures"
date: 2019-02-01
---
  title: Missouri outdoor adventures
  author: Outdoorsman
  email: jaredrosine82@gmail.com
  description: > # this means to ignore newlines until "baseurl:"This blog is all about the natural beauty of missouri's wilderness."
  # social links
  twitter_username: your-twitter-handle
  github_username:  your-github-handle

  show_excerpts: true # set to false to remove excerpts on the homepage

  theme: minima
